server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/identitydb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false

#jwt:
#  secret: verysecretkeythatisatleast32byteslongforhmac
#  expiration: 86400000 # 1 hour

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
